version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
  build:
    commands:
      - zip -r -j deployment_package_index_photos.zip "lambda_functions/index_photos.py"
      - zip -r -j deployment_package_search_photos.zip "lambda_functions/search_photos.py"
  post_build:
    commands:
      - echo "Updating Index and Search Lambda Functions"
      - aws lambda update-function-code --function-name Cloud-A3-Index-Photos --zip-file fileb://deployment_package_index_photos.zip
      - aws lambda wait function-updated --function-name Cloud-A3-Index-Photos
      - aws lambda update-function-configuration --function-name Cloud-A3-Index-Photos --handler Cloud-A3-Index-Photos.lambda_handler
      - aws lambda update-function-code  --function-name Cloud-A3-Search-Photos --zip-file fileb://deployment_package_search_photos.zip
      - aws lambda wait function-updated --function-name Cloud-A3-Search-Photos
      - aws lambda update-function-configuration --function-name Cloud-A3-Search-Photos --handler Cloud-A3-Search-Photos.lambda_handler
      - echo "Done Updating Index and Search Lambda Functions!!"